/**
 * @fileoverview This file was generated by the Angular template compiler. Do not edit.
 *
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride,checkTypes}
 * tslint:disable
 */ 
var styles = ["div[_ngcontent-%COMP%]{\r\n    padding: 20px;\r\n    border: 1px solid;\r\n}\r\n\r\n\r\n.example-tree-node[_ngcontent-%COMP%] {\r\n    display: flex;\r\n    align-items: center;\r\n  }\r\n\r\n  body[_ngcontent-%COMP%] { \r\n    font-family: Roboto, Arial, sans-serif;\r\n    margin: 0;\r\n  }\r\n  \r\n  .basic-container[_ngcontent-%COMP%] {\r\n    padding: 30px;\r\n  }\r\n  \r\n  .version-info[_ngcontent-%COMP%] {\r\n    font-size: 8pt;\r\n    float: right;\r\n  }\r\n\r\n  \r\n\r\n\r\n.material-icons[_ngcontent-%COMP%] {  \r\n   \r\n   -webkit-font-smoothing: antialiased;\r\n\r\n   \r\n   text-rendering: optimizeLegibility;\r\n\r\n   \r\n   -moz-osx-font-smoothing: grayscale;\r\n\r\n   \r\n   font-feature-settings: 'liga';\r\n}"];
export { styles as styles };
//# sourceMappingURL=parent.component.scss.shim.ngstyle.js.map